#!/usr/bin/bash
function Mcpp() {
        name="$1";
        g++ "$name" -o "${name%.*}"
}

function Rcpp() {
        Mcpp "$1";
        if [ -f "${1%.*}" ]; then
                ./"${1%.*}"
        fi
        if [ -f "${1%.*}" ]; then
                rm "${1%.*}"
        fi
}

function Mc() {
        name="$1";
        gcc "$name" -o "${name%.*}" -lm
}

function Rc() {
        Mc "$1";
        if [ -f "${1%.*}" ]; then
                ./"${1%.*}"
        fi

        rm "${1%.*}"

}

function iorun() {
        if [[ "$1" == "-h" ]]; then
                echo "usage: iorun [c/cpp_file] [-o output_file] [-i input_file]"
                echo
                echo "defaults: input_file=input.txt and output_file=output.txt"
                echo "          does a normal run if input.txt not found"
                return 1;
        fi

        extension="${1#*.}";
        c_file="$1"
        file_name="${1%.*}"
        shift;

        if [[ ! -f $c_file ]]; then
                echo "file not found."
                return 1;
        fi

        if [[ "$extension" != "cpp" ]] && [[ "$extension" != "c" ]]; then
                echo "not a valid file."
                return 1;
        fi

        output_file=""
        input_file=""
        while test $# -gt 0; do
                case "$1" in
                        -o)
                                shift
                                output_file="$1"
                                shift
                                ;;
                        -i)
                                shift
                                input_file="$1"
                                shift
                                ;;
                esac
        done

        if [[ $output_file == '' ]]; then
                echo "default ouput is output.txt"
                output_file="output.txt"
        fi

        if [[ $input_file == '' ]]; then
                echo "default input is input.txt"
                input_file="input.txt"
        fi

        if [[ ! -f $input_file ]]; then
                echo "input file not present, defaulting to normal run."
                run $c_file
                return 1;
        fi

        if [[ "$extension" == "c" ]]; then
                Mc $c_file
        elif [[ "$extension" == "cpp" ]]; then
                Mcpp $c_file
        fi

        if [ -f "$file_name" ]; then
                ./"$file_name" < $input_file > $output_file
        fi
        if [ -f "$file_name" ]; then
                rm "$file_name"
        fi
}

iorun
